<a href="https://colab.research.google.com/github/DiegoRodolico/batalla_naval/blob/main/Copia_de_Copia_de_Batalla_Naval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Se pondran en grupos de a 2. Entrega hasta el 4/3/2026.**

Deberan enviar a martin.pustilnik@unahur.edu.ar un link a su documento de colab que implemente la batalla naval.

Integrante 1 (Nombre, Dni, mail):

Integrante 2 (Nombre, Dni, mail):

No se aceptaran codigos iguales a otros equipos, ni generados por IA.

¿qué debe hacer el programa?

1_ El programa debera pedir el tamaño del tablero (filas, columnas) al principio para dimensionar el tablero (un arreglo de dos dimensiones, como se sugiere en el codigo de ejemplo) del jugador1 y del jugador2, de igual dimensiones.

2_ Se deben crear los dos tableros

3_ se deben pedir 4 barcos de 1x1 para cada jugador que deben que dar dentro de las dimensiones del tablero y no se pueden solapar. En caso de que esto no se cumpla, se debe arrojar una excepcion 'raise ExceptionType("Posición invalida")'.

4_ en cada turno, cada jugador emitira "disparos" denotados por coordendas, por ejemplo '2,3'.
El sistema informara algua de estas opciones:
Agua: si no no toca ningun barco.
Hundido: si le pega a un baro enemigo.
Gano: en caso de haber hundido todos los barcos enemigos.

**El juego se termina cuando algun jugador gana.**  Al finalizar se debe mostrar el tablero con los barcos de cada jugador (indicando que barcos estan hundidos).

Ayuda: Se recomienda tener para cada jugador: un tablero con barcos y otro con los disparos del enemigo.

In [1]:
#Batalla naval realizada por Ledesma Barrios Ezequiel DNI 35337617 mail: ledesmabarrioseze@gmail.com  y Rodolico Diego DNI 38465737 mail: rodolicodiego@gmail.com.

# Hicimos una modificación a las posiciones del tablero para que sea más intuitivo para el usuario
# Las coordenadas arrancan de 1 tanto para filas como para columnas.
# Ya que sino las primeras filas y columnas tenian 0 de valor.
# El programa imprime tableros tanto de barcos como de tiros.
# El tablero de barcos aparece al colocar barcos y al terminar juego, el de tiros siempre al iniciar un tiro
# Utilizamos try except por si el usuario no ingresa números algebraicos, no lo conocíamos pero investigamos a modo de aprendizaje mediante IA para usarlo.
# Solo para sacar de ella el concepto y la lógica detrás.
# El programa es 100% nuestro. Esperamos que sea de su agrado

#Comienzo del código

#Importamos Numpy

import numpy as np

#Funciones y procedimientos

def configurarDimensionesDelTablero():
    filas = 0
    columnas = 0
    while (filas * columnas) < 4:
        try:
            filas = int(input("Ingresá cantidad de filas: "))
            columnas = int(input("Ingresá cantidad de columnas: "))
            if (filas * columnas) < 4:
                print("Tablero muy chico")
                continue
        except ValueError:
            print("Ingresá números algebraicos para el tamaño del tablero")
            continue
    return filas, columnas

def crearUnTableroDe_Y_(cantidadFilas, cantidadColumnas):
    return np.zeros((cantidadFilas, cantidadColumnas), int)

def colocarBarcosEn_De_Y_DelJugador_(unTablero, cantidadFilas, cantidadColumnas, unJugador):
    print(f"Jugador {unJugador}, colocá tus 4 barcos (1x1)")

    for i in range(4):
        barcoValido = False
        while barcoValido == False:
            try:
                f = int(input(f"Tu Barco {i + 1} está en fila: ")) - 1
                c = int(input(f"Tu Barco {i + 1} está en columna: ")) - 1

                if f < 0 or f >= cantidadFilas or c < 0 or c >= cantidadColumnas:
                    print("Posición fuera de tablero")
                    continue

                elif unTablero[f, c] == 1:
                    print("Ya hay un barco en esa posición")
                    continue

                else:
                  unTablero[f, c] = 1
                  barcoValido = True

            except ValueError:
                print("Debés ingresar un número entero en sistema algebraico!")
                continue

    print(f"Así quedaron tus barcos, jugador {unJugador} ")
    print(unTablero)

def realizarUnDisparoEn_De_Y_Y_DelJugador_(unTableroEnemigo, unRadarPropio, cantidadFilas, cantidadColumnas, unJugadorAtacante):
    print(f"Turno Jugador {unJugadorAtacante}")

    while True:
        print(f"Tu radar de disparos (1=Hundido, -1=Agua, 0=No disparaste):")
        print(unRadarPropio)

        try:
            f = int(input("Fila donde disparás: ")) - 1
            c = int(input("Columna donde disparás: ")) - 1

            if f < 0 or f >= cantidadFilas or c < 0 or c >= cantidadColumnas:
                print("Posición fuera de juego. Reintentá dentro del tablero!")
                continue

            elif unRadarPropio[f, c] != 0:
                print("Ya disparaste en ese lugar! Reintentá en una posición nueva")
                continue

            elif unTableroEnemigo[f, c] == 1:
                unTableroEnemigo[f, c] = 0
                unRadarPropio[f, c] = 1
                print("BARCO HUNDIDO!!! FELICITACIONES")
                return True
            else:
                unRadarPropio[f, c] = -1
                print("AGUA!!! SUERTE LA PRÓXIMA")
                return False

        except ValueError:
            print("Debés ingresar un número entero en sistema algebraico!")
            continue

def realizarUnaRondaEnLosTableros_Y_Y_De_Y_ParaHundirBarcos_Y_(Tablero1, Tablero2, Radar1, Radar2, cantidadFilas, cantidadColumnas, BarcosJ1, BarcosJ2):
    if realizarUnDisparoEn_De_Y_Y_DelJugador_(Tablero2, Radar1, cantidadFilas, cantidadColumnas, 1) == True:
        BarcosJ1 = BarcosJ1 + 1

    if realizarUnDisparoEn_De_Y_Y_DelJugador_(Tablero1, Radar2, cantidadFilas, cantidadColumnas, 2) == True:
        BarcosJ2 = BarcosJ2 + 1

    return BarcosJ1, BarcosJ2

def verificarSiElJuegoFinalizoSegunLosBarcos_Y_(HundidosJ1, HundidosJ2):
    juegoFinalizado = False
    if HundidosJ1 == 4 and HundidosJ2 == 4:
        print("EMPATE! Ambos hundieron todo")
        juegoFinalizado = True
    elif HundidosJ1 == 4:
        print("GANÓ EL JUGADOR 1!")
        juegoFinalizado = True
    elif HundidosJ2 == 4:
        print("GANÓ EL JUGADOR 2!")
        juegoFinalizado = True
    else:
        juegoFinalizado = False

    return juegoFinalizado

# Procedimiento Principal que engloba todo el programa

def iniciarBatallaNaval():

    filas, columnas = configurarDimensionesDelTablero()

    tablero1 = crearUnTableroDe_Y_(filas, columnas)
    tablero2 = crearUnTableroDe_Y_(filas, columnas)
    radar1 = crearUnTableroDe_Y_(filas, columnas)
    radar2 = crearUnTableroDe_Y_(filas, columnas)

    hundidosJ1 = 0
    hundidosJ2 = 0

    colocarBarcosEn_De_Y_DelJugador_(tablero1, filas, columnas, 1)
    colocarBarcosEn_De_Y_DelJugador_(tablero2, filas, columnas, 2)

    juegoTerminado = False

    while juegoTerminado == False:
        hundidosJ1, hundidosJ2 = realizarUnaRondaEnLosTableros_Y_Y_De_Y_ParaHundirBarcos_Y_(tablero1, tablero2, radar1, radar2, filas, columnas, hundidosJ1, hundidosJ2)
        juegoTerminado = verificarSiElJuegoFinalizoSegunLosBarcos_Y_(hundidosJ1, hundidosJ2)

    print("Así quedaron sus tableros finales")
    print("Jugador 1:")
    print(tablero1)
    print("Jugador 2:")
    print(tablero2)

# Programa

iniciarBatallaNaval()



Ingresá cantidad de filas: 5
Ingresá cantidad de columnas: 4
Jugador 1, colocá tus 4 barcos (1x1)
Tu Barco 1 está en fila: 1
Tu Barco 1 está en columna: 1
Tu Barco 2 está en fila: 2
Tu Barco 2 está en columna: 1
Tu Barco 3 está en fila: 1
Tu Barco 3 está en columna: 1
Ya hay un barco en esa posición
Tu Barco 3 está en fila: 1
Tu Barco 3 está en columna: 3
Tu Barco 4 está en fila: 3
Tu Barco 4 está en columna: 1
Así quedaron tus barcos, jugador 1 
[[1 0 1 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Jugador 2, colocá tus 4 barcos (1x1)
Tu Barco 1 está en fila: 2
Tu Barco 1 está en columna: 3
Tu Barco 2 está en fila: 4
Tu Barco 2 está en columna: 2
Tu Barco 3 está en fila: 1
Tu Barco 3 está en columna: 2
Tu Barco 4 está en fila: 3
Tu Barco 4 está en columna: 4
Así quedaron tus barcos, jugador 2 
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 1 0 0]
 [0 0 0 0]]
Turno Jugador 1
Tu radar de disparos (1=Hundido, -1=Agua, 0=No disparaste):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Fila